# Generated by Django 4.2.7 on 2023-12-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardquest', '0002_rename_pokemoncards_pokemoncard_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemoncard',
            name='card_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
